# Generated by Django 6.1.1 on 2026-09-04 06:42

import django.core.validators
import django.db.models.deletion
import django_openrouter.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OpenRouterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="OpenRouter model id, e.g. anthropic/claude-3.5-sonnet",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("context_length", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "pricing",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-token prices: prompt, completion, optional request/image.",
                    ),
                ),
                ("supported_parameters", models.JSONField(blank=True, default=list)),
                ("modality", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "OpenRouter model",
                "verbose_name_plural": "OpenRouter models",
                "ordering": ["model_id"],
            },
        ),
        migrations.CreateModel(
            name="UsageProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.SlugField(
                        help_text="Stable slug used in code, e.g. chat, translation.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("max_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("max_requests_per_day", models.PositiveIntegerField(blank=True, null=True)),
                ("max_requests_per_month", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "budget_usd_per_day",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                (
                    "budget_usd_per_month",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                (
                    "only_free_models",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, only models with zero catalog price may be used.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profiles",
                        to="django_openrouter.openroutermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage profile",
                "verbose_name_plural": "Usage profiles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OpenRouterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "api_key",
                    django_openrouter.fields.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="Leave empty to use OPENROUTER_API_KEY / settings.OPENROUTER['API_KEY'].",
                    ),
                ),
                ("base_url", models.URLField(default="https://openrouter.ai/api/v1")),
                (
                    "request_timeout",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="HTTP timeout in seconds.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Retries per model on transport / 5xx errors before fallback.",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Global kill switch. When off, every chat() call fails.",
                    ),
                ),
                (
                    "default_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="django_openrouter.usageprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "OpenRouter settings",
                "verbose_name_plural": "OpenRouter settings",
            },
        ),
        migrations.CreateModel(
            name="UsageProfileFallback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fallback_usages",
                        to="django_openrouter.openroutermodel",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fallback_links",
                        to="django_openrouter.usageprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fallback model",
                "verbose_name_plural": "Fallback models",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="usageprofile",
            name="fallback_models",
            field=models.ManyToManyField(
                blank=True,
                related_name="fallback_profiles",
                through="django_openrouter.UsageProfileFallback",
                to="django_openrouter.openroutermodel",
            ),
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("status_code", models.PositiveIntegerField()),
                ("error_message", models.TextField(blank=True, null=True)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=10, default=Decimal("0"), max_digits=16),
                ),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_logs",
                        to="django_openrouter.openroutermodel",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_logs",
                        to="django_openrouter.usageprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request log",
                "verbose_name_plural": "Request logs",
                "ordering": ["-created_at"],
                "permissions": [("view_usage_logs", "Can view usage logs")],
                "indexes": [
                    models.Index(fields=["profile", "created_at"], name="or_log_profile_created")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="usageprofilefallback",
            constraint=models.UniqueConstraint(
                fields=("profile", "model"), name="django_openrouter_fallback_unique"
            ),
        ),
    ]
