# Generated by Django 6.1.1 on 2026-09-04 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_openrouter", "0003_usageprofile_model_chain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usageprofilefallback",
            name="model",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fallback_usages",
                to="django_openrouter.openroutermodel",
            ),
        ),
    ]
