# Generated by Django 6.1.1 on 2026-09-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_openrouter', '0005_alter_openroutermodel_completion_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openroutersettings',
            name='max_parallel_requests',
            field=models.PositiveIntegerField(default=10, help_text='Max concurrent HTTP requests to OpenRouter in this process. 0 = unlimited.'),
        ),
        migrations.AddField(
            model_name='openroutersettings',
            name='streaming_enabled',
            field=models.BooleanField(default=False, help_text='Allow SSE streaming via stream()/astream() and chat(stream=True).'),
        ),
    ]
