# Generated by Django 6.1.1 on 2026-09-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_openrouter', '0006_openroutersettings_streaming_parallel'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='username',
            field=models.CharField(db_index=True, default='anonymous', help_text="Authenticated user's username, or 'anonymous'.", max_length=150),
        ),
    ]
